// SPDX-FileCopyrightText: 2026 aTox contributors
//
// SPDX-License-Identifier: GPL-3.0-only

package ltd.evilcorp.core.platform

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class JvmPlatformServicesTest {

    private val platformServices = JvmPlatformServices()

    @Test
    fun testFormatDate() {
        val timestamp = 1717142400000L // 2024-05-31 08:00:00 UTC/Local depending on local timezone
        val formatted = platformServices.formatDate(timestamp)
        assertNotNull(formatted)
        // Check date format pattern matches YYYY-MM-DD
        assertTrue(formatted.matches(Regex("\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}")))
    }

    @Test
    fun testGenerateSecureBytes() {
        val size = 32
        val bytes = platformServices.generateSecureBytes(size)
        assertEquals(size, bytes.size)
        
        // Generate another array and verify they are not identical (due to randomness)
        val bytes2 = platformServices.generateSecureBytes(size)
        assertEquals(size, bytes2.size)
        
        var isDifferent = false
        for (i in 0 until size) {
            if (bytes[i] != bytes2[i]) {
                isDifferent = true
                break
            }
        }
        assertTrue(isDifferent, "Randomly generated bytes should be different")
    }

    @Test
    fun testZipAndUnzip() {
        val file1Content = "Hello World".toByteArray(Charsets.UTF_8)
        val file2Content = "Kotlin is awesome".toByteArray(Charsets.UTF_8)
        
        val filesToZip = mapOf(
            "file1.txt" to file1Content,
            "sub/file2.txt" to file2Content
        )
        
        val zippedBytes = platformServices.zip(filesToZip)
        assertTrue(zippedBytes.isNotEmpty(), "Zipped bytes should not be empty")
        
        val unzippedFiles = platformServices.unzip(zippedBytes)
        assertEquals(2, unzippedFiles.size)
        
        assertTrue(unzippedFiles.containsKey("file1.txt"))
        assertTrue(unzippedFiles.containsKey("sub/file2.txt"))
        
        assertEquals("Hello World", String(unzippedFiles["file1.txt"]!!, Charsets.UTF_8))
        assertEquals("Kotlin is awesome", String(unzippedFiles["sub/file2.txt"]!!, Charsets.UTF_8))
    }
}
